config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :users, only: [:index, :show, :edit, :update] do
    post 'ban', as: :ban, on: :member
  end

  resources :blogs
  resources :posts
  resources :comments
  resources :ratings, only: [:create]
  resources :search, only: [:index, :create], as: :searchs

  mount RedactorRails::Engine => '/redactor_rails'
end

app/models/blog.rb
# frozen_string_literal: true
class Blog < ActiveRecord::Base
  validates :name, :uri, presence: true
  validates :uri, uniqueness: true
  validates :name, length: { maximum: 255 }
  validates :uri,  length: { maximum: 32 }

  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :posts, dependent: :destroy

  def to_param
    uri
  end
end

# == Schema Information
#
# Table name: blogs
#
#  created_at  :datetime         not null
#  description :text(65535)
#  id          :integer          not null, primary key
#  name        :string(255)
#  updated_at  :datetime         not null
#  uri         :string(255)
#  user_id     :integer
#
# Indexes
#
#  index_blogs_on_uri      (uri)
#  index_blogs_on_user_id  (user_id)
#

app/controllers/blogs_controller.rb
# frozen_string_literal: true
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource only: [:new, :destroy, :edit, :update]

  def index
    @blogs = Blog.all
  end

  def show
    @posts = @blog.posts.newest.page(params[:page]).per(15)
  end

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)
    @blog.author = current_user
    if @blog.save
      redirect_to @blog, notice: t('blogs.created')
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: t('blogs.updated')
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: t('blogs.deleted')
  end

  private

  # setup blog
  def set_blog
    @blog = Blog.find_by(uri: params[:id])
  end

  # whitelist for params
  def blog_params
    params.require(:blog).permit(:name, :description, :uri)
  end
end

app/views/blogs/_form.html.slim
.container
  .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
    h1
      = @blog.persisted? ? t('blogs.edit') : t('blogs.create')
    = form_for(@blog, html: { role: 'form', class: 'form form-horizontal' } ) do |f|
      = form_errors(@blog)
      .form-group
        = f.label :name
        br
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :description
        br
        = f.text_area :description, class: 'form-control redactor', style: 'width:100%;', rows: 20
      .form-group
        = f.label :uri
        br
        = f.text_field :uri, class: 'form-control'
      hr
      .form-group
        = f.submit t('controls.save'), class: 'btn btn-success'

app/views/blogs/edit.html.slim
= render 'form'

app/views/blogs/index.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      h1
        | Блоги
      = link_to t('blogs.create'), new_blog_path, class: 'btn btn-success pull-right' if can? :create, Blog
      ul
        - @blogs.each do |blog|
          li
            h3
              = link_to blog.name, blog_path(blog)
            small
              = blog.description
              |  // 
              = blog.author.name
            br
            = link_to 'Изменить', edit_blog_path(blog), class: 'btn btn-primary' if can? :edit, blog
            = link_to 'Удалить', blog, method: :delete, data: { confirm: 'Вы точно хотите удалить?' }, class: 'btn btn-danger' if can? :destroy, blog

app/views/blogs/new.html.slim
= render 'form'

app/views/blogs/show.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      - if can? :create, Post
        .row
          = link_to t('posts.create'), new_post_path, class: 'btn btn-success pull-right'
      h1
        = @blog.name
      p
        = @blog.description
      - @posts.each do |post|
        .post-preview
          .row
            |  <a href="
            = post_path(post)
            | "> 
            .col-lg-3.text-center
              = image_tag post.image.url(:preview), class: 'preview'
            .col-lg-9
              h2.post-title
                = post.name
              = link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_post_path(post), class: 'label label-primary', title: t('controls.edit') if can? :edit, post
              = link_to '<i class="fa fa-trash"></i>'.html_safe, post, method: :delete, data: { confirm: t('are_u_sure') }, class: 'label label-danger', title: t('controls.destroy') if can? :destroy, post
              h3.post-subtitle
                = post.content_cut
          p.post-meta
            = t('posts.posted_by')
            = link_to post.author.name, user_path(post.author)
            = t('on')
            = l post.created_at, format: :short
        hr
      = paginate @posts