config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :users, only: [:index, :show, :edit, :update] do
    post 'ban', as: :ban, on: :member
  end

  resources :blogs
  resources :posts
  resources :comments
  resources :ratings, only: [:create]
  resources :search, only: [:index, :create], as: :searchs

  mount RedactorRails::Engine => '/redactor_rails'
end

app/controllers/search_controller.rb
# frozen_string_literal: true
class SearchController < ApplicationController
  def index; end

  def create
    @posts = Post.search do
      with(:blog_id, params[:blog_id]) if params[:blog_id].present?
      fulltext params[:query] do
        boost_fields name: 5.0
      end
      paginate page: params[:page], per_page: 10
    end.results

    render action: :index
  end
end

app/views/search/index.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      h1
        | Поиск
      .row
        = form_tag searchs_path, :method => :post, class: 'form form-inline' do
          .col-sm-4
            = text_field_tag :query, params[:query], class: 'form-control input-lg'
          .col-sm-4
            = select_tag :blog_id, options_for_select(Blog.all.collect { |b| [b.name, b.id] }, params[:blog_id]), { include_blank: 'Любой', class: 'form-control input-lg' }
          .col-sm-4
            = submit_tag "Поиск!", class: 'btn btn-primary pull-right'
      - unless @posts.nil?
        - @posts.each do |post|
          .post-preview
            .row
              |  <a href="
              = post_path(post)
              | "> 
              .col-lg-3.text-center
                = image_tag post.image.url(:preview), class: 'preview'
              .col-lg-9
                h2.post-title
                  = post.name
                = link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_post_path(post), class: 'label label-primary', title: t('controls.edit') if can? :edit, post
                = link_to '<i class="fa fa-trash"></i>'.html_safe, post, method: :delete, data: { confirm: t('are_u_sure') }, class: 'label label-danger', title: t('controls.destroy') if can? :destroy, post
                h3.post-subtitle
                  = post.content_cut
            p.post-meta
              = t('posts.posted_by')
              = link_to post.author.name, user_path(post.author)
              = t('on')
              = l post.created_at, format: :short
          hr
        = paginate @posts