config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :users, only: [:index, :show, :edit, :update] do
    post 'ban', as: :ban, on: :member
  end

  resources :blogs
  resources :posts
  resources :comments
  resources :ratings, only: [:create]
  resources :search, only: [:index, :create], as: :searchs

  mount RedactorRails::Engine => '/redactor_rails'
end

app/models/user.rb
# frozen_string_literal: true
class User < ActiveRecord::Base
  include Sortable

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  devise :database_authenticatable, :registerable, :confirmable, :recoverable,
         :rememberable, :trackable, :validatable, :omniauthable

  before_validation :set_role
  after_create :user_soc

  mount_uploader :image, AvatarUploader
  mount_uploader :wallpaper, ImageUploader

  has_many :posts, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_many :providers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :socials

  validates :name, presence: true
  validates :email, uniqueness: true
  validates :email, format: { without: TEMP_EMAIL_REGEX }, on: :update

  enum sex: { male: 1, female: 2 }

  def full_name
    name || email
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Provider.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.find_by(email: email) if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          # username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0, 20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    email && email !~ TEMP_EMAIL_REGEX
  end

  def user_soc
    socials.create(name: :twitter)
    socials.create(name: :vk)
    socials.create(name: :github)
    socials.create(name: :linkedin)
    socials.create(name: :facebook)
    socials.create(name: :skype)
    socials.create(name: :personal_site)
  end

  private

  def set_role
    self.role = 'user' unless role
  end
end

# == Schema Information
#
# Table name: users
#
#  confirmation_sent_at   :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string(255)
#  description            :text(65535)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  id                     :integer          not null, primary key
#  image                  :string(255)
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string(255)
#  name                   :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  role                   :string(255)
#  sex                    :integer          default("male")
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string(255)
#  updated_at             :datetime         not null
#  wallpaper              :string(255)
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :ban]
  load_and_authorize_resource only: [:new, :destroy, :edit, :update, :ban]

  layout 'simple', only: [:show, :edit]

  def index
    @users = User.alphabetical.page(params[:page]).per(50)
  end

  def show
    # authorize! :read, @user
  end

  def edit
    @social = Social.create(name: :twitter)
    # authorize! :update, @user
  end

  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, bypass: true)
        format.html { redirect_to @user, notice: t('users.updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] # && params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, bypass: true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  #   def destroy
  #     # authorize! :delete, @user
  #     @user.destroy
  #     respond_to do |format|
  #       format.html { redirect_to root_url }
  #       format.json { head :no_content }
  #     end
  #   end

  def ban
    if @user.role == 'user'
      @user.update(role: 'banned')
      redirect_to @user, notice: 'user забанен'
    else
      @user.update(role: 'user')
      redirect_to @user, notice: 'user разбанен'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [:name, :email, :image, :sex, :description, :wallpapers] # extend with your own params
    accessible << [:password, :password_confirmation] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/views/users/_form.html.slim
= render 'users/header', user: @user
.container
  .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2
    h1
      | Редактировать профиль
    = form_for(@user, html: { role: 'form', class: 'form form-horizontal' } ) do |f|
      = form_errors(@user)
      .form-group
        = f.label :name, t('users.name')
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :email, 'E-mail'
        = f.text_field :email, class: 'form-control'
      = render 'users/socials'
      .form-group
        = f.label :password, t('users.new_password')
        = f.text_field :password, class: 'form-control'
      .form-group
        = f.label :sex, t('users.sex')
        label
          i.fa.fa-male
          = f.radio_button :sex, :male
          = t('users.man')
        label
          i.fa.fa-female
          = f.radio_button :sex, :female
          = t('users.woman')
      .form-group
        = f.label :description, t('users.description')
        = f.text_area :description, class: 'form-control redactor'
      .row
        .col-lg-6
          .fileUpload.btn.btn-primary.form-group
            span
              i.glyphicon.glyphicon-picture
              = t('users.upload_avatar')
            = f.file_field :image, class: 'upload'
          = f.hidden_field :image_cache
        .col-lg-6
          .fileUpload.btn.btn-primary.form-group.pull-right
            span
              i.glyphicon.glyphicon-picture
              = t('users.upload_wallpaper')
            = f.file_field :wallpaper, class: 'upload'
          = f.hidden_field :wallpaper_cache
      hr
      .form-group
        = f.submit t('controls.save'), class: 'btn btn-success'

app/views/users/_header.html.slim
| <header class="intro-header profile-widget panel-shadow" style="background-image: url('
= user.wallpaper.url
| ')"> 
.row
  .col-sm-12
    .image-container
      = image_tag user.image.url(:thumb), class: 'avatar'
  .col-sm-12
    .details.text-white
      h4
        |  <i class="fa fa-
        = user.sex
        | ">
        = user.full_name
      div
        = mail_to user.email, class: 'btn btn-info' do
          i.fa.fa-envelope-o
          = user.email
        = link_to "Редактировать профиль", edit_user_path(user), class: 'btn btn-success' if can? :edit, user
        - if user.role == 'banned'
          = link_to "Разбанить", ban_user_path(user), method: :post, class: 'btn btn-primary' if can? :ban, user
        - else
          = link_to "Забанить",  ban_user_path(user), method: :post, class: 'btn btn-danger' if can? :ban, user

app/views/users/_socials.html.slim
= current_user.socials.each do |social|
  .form-group
    = social.label :name
    = social.text_field :name, class: 'form-control'

app/views/users/edit.html.slim
= render 'form'

app/views/users/finish_signup.html.slim
#add-email.container
  h1
    | Add Email
  = form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f|
    - if @show_errors && current_user.errors.any?
      #error_explanation
        - current_user.errors.full_messages.each do |msg|
          = msg
          br
    .form-group
      = f.label :email
      .controls
        = f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com'
        p.help-block
          | Please confirm your email address. No spam.
    .actions
      = f.submit 'Continue', :class => 'btn btn-primary'

app/views/users/index.html.slim
.container
  .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
    h1
      | Пользователи
    - @users.each do |user|
      .col-md-4
        .panel.widget
          .panel-body.text-center.bg-center.user-panel
            .row.row-table
              .col-xs-12.text-white
                |  <a href="
                = user_path(user.id)
                | "> 
                = image_tag user.image.url(:thumb), class: 'img-thumbnail img-circle thumb128'
                h3.m0
                  = user.name
          .panel-body.text-center.bg-gray-darker
            .row.row-table
              .col-xs-4
                a.text-white[href="#"]
                  em.fa.fa-twitter.fa-2x
              .col-xs-4
                a.text-white[href="#"]
                  em.fa.fa-github.fa-2x
              .col-xs-4
                a.text-white[href="#"]
                  em.fa.fa-linkedin.fa-2x
          .list-group
            a.list-group-item[href="#"]
              span.label.label-primary.pull-right
                | 300
              em.fa.fa-fw.fa-pencil.text-muted
              | Posts 
            a.list-group-item[href="#"]
              span.label.label-primary.pull-right
                | 15
              em.fa.fa-fw.fa-comments.text-muted
              | Comments 
    = paginate @users

app/views/users/show.html.slim
= render 'users/header', user: @user
.container
  .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
    h1
      = t('users.description')
    div
      = clean_post @user.description