config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
  resources :users, only: [:index, :show, :edit, :update] do
    post 'ban', as: :ban, on: :member
  end

  resources :blogs
  resources :posts
  resources :comments
  resources :ratings, only: [:create]
  resources :search, only: [:index, :create], as: :searchs

  mount RedactorRails::Engine => '/redactor_rails'
end

app/views/inc/_footer.html.slim
hr
footer
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        ul.list-inline.text-center
          li
            a[href="#"]
              span.fa-stack.fa-lg
                i.fa.fa-circle.fa-stack-2x
                i.fa.fa-twitter.fa-stack-1x.fa-inverse
          li
            a[href="#"]
              span.fa-stack.fa-lg
                i.fa.fa-circle.fa-stack-2x
                i.fa.fa-facebook.fa-stack-1x.fa-inverse
          li
            a[href="#"]
              span.fa-stack.fa-lg
                i.fa.fa-circle.fa-stack-2x
                i.fa.fa-github.fa-stack-1x.fa-inverse
        p.copyright.text-muted
          | Copyright © UfaCode - уфимское сообщество ИТ ремесленников, 2015

app/views/inc/_header.html.slim
header.intro-header[style="background-image: url('/img/home-bg.jpg')"]
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .site-heading
          h1
            | Ufa
            span
              | Code
          hr.small
          span.subheading
            | сообщество уфимских ИТ ремесленников

app/views/inc/_nav.html.slim
nav.navbar.navbar-default.navbar-custom.navbar-fixed-top
  .container-fluid
    .navbar-header.page-scroll
      button.navbar-toggle[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      |  <a class="navbar-brand" href="
      = root_path
      | " title="UfaCode">
      b
        | //
      |  Ufa
      span
        | Code
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Лента', posts_path
        li
          = link_to 'Блоги', blogs_path
        li
          = link_to 'Пользователи', users_path
        - if user_signed_in?
          li
            = link_to current_user do
              i.fa.fa-user
              = current_user.full_name
          li
            = link_to destroy_user_session_path, method: :delete do
              i.fa.fa-sign-out
              = t('users.signout')
        - else
          li
            = link_to 'Войти', new_user_session_path
          li
            = link_to 'Зарегистироваться', new_user_registration_path

app/views/inc/_nav_simple.html.slim
nav.navbar.navbar-inverse.navbar-custom-simple.navbar-fixed-top
  .container-fluid
    .navbar-header.page-scroll
      button.navbar-toggle[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: "navbar-brand", title: "UfaCode" do
        b>
          | //
        | Ufa
        span
          | Code
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Лента', posts_path
        li
          = link_to 'Блоги', blogs_path
        li
          = link_to 'Пользователи', users_path
        - if user_signed_in?
          li
            = link_to current_user do
              i.fa.fa-user
              = current_user.full_name
          li
            = link_to destroy_user_session_path, method: :delete do
              i.fa.fa-sign-out
              = t('users.signout')
        - else
          li
            = link_to 'Войти', new_user_session_path
          li
            = link_to 'Зарегистироваться', new_user_registration_path